export const GET_TOTAL_DEVICE = "GET_TOTAL_DEVICE";
export const GET_ACTIVE_DEVICE = "GET_ACTIVE_DEVICE";
export const GET_INACTIVE_DEVICE = "GET_INACTIVE_DEVICE";
export const GET_ALL_TICKETS = "GET_ALL_TICKETS";
export const GET_OPEN_TICKETS = "GET_OPEN_TICKETS";
export const GET_CLOSED_TICKETS = "GET_CLOSED_TICKETS";
export const GET_DEVICE_FAIL = "GET_DEVICE_FAIL";
