/* TASKS */
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const CHANGE_USERS_PAGE_SIZE = "CHANGE_USERS_PAGE_SIZE";
export const CHANGE_USERS_PAGE_NUMBER = "CHANGE_USERS_PAGE_NUMBER";

export const CHANGE_USERS_SORT = "CHANGE_USERS_SORT";
export const CHANGE_USERS_SEARCH_TEXT = "CHANGE_USERS_SEARCH_TEXT";
