/* TASKS */
export const GET_COMPONENTS = "GET_COMPONENTS";
export const GET_COMPONENTS_SUCCESS = "GET_COMPONENTS_SUCCESS";
export const GET_COMPONENTS_FAIL = "GET_COMPONENTS_FAIL";

export const CHANGE_COMPONENT_PAGE_SIZE = "CHANGE_COMPONENT_PAGE_SIZE";
export const CHANGE_COMPONENT_PAGE_NUMBER = "CHANGE_COMPONENT_PAGE_NUMBER";

export const CHANGE_COMPONENT_SORT = "CHANGE_COMPONENT_SORT";
export const CHANGE_COMPONENT_SEARCH_TEXT = "CHANGE_COMPONENT_SEARCH_TEXT";

export const CHANGE_COMPONENT_NOTI_TYPE = "CHANGE_COMPONENT_NOTI_TYPE";

export const CHANGE_COMPONENT_DEVICE_TYPE = "CHANGE_COMPONENT_DEVICE_TYPE";
