/* TASKS */
export const GET_RECORDING = "GET_RECORDING";
export const GET_RECORDING_SUCCESS = "GET_RECORDING_SUCCESS";
export const GET_RECORDING_FAIL = "GET_RECORDING_FAIL";

export const CHANGE_RECORDING_PAGE_SIZE = "CHANGE_RECORDING_PAGE_SIZE";
export const CHANGE_RECORDING_PAGE_NUMBER = "CHANGE_RECORDING_PAGE_NUMBER";

export const CHANGE_RECORDING_SORT = "CHANGE_RECORDING_SORT";
export const CHANGE_RECORDING_SEARCH_TEXT = "CHANGE_RECORDING_SEARCH_TEXT";

export const CHANGE_RECORDING_NOTI_TYPE = "CHANGE_RECORDING_NOTI_TYPE";
