/* TASKS */
export const GET_COMPONENT_HEALTH = "GET_COMPONENT_HEALTH";
export const GET_COMPONENT_HEALTH_SUCCESS = "GET_COMPONENT_HEALTH_SUCCESS";
export const GET_COMPONENT_HEALTH_FAIL = "GET_COMPONENT_HEALTH_FAIL";

export const CHANGE_COMPONENT_HEALTH_PAGE_SIZE =
  "CHANGE_COMPONENT_HEALTH_PAGE_SIZE";
export const CHANGE_COMPONENT_HEALTH_PAGE_NUMBER =
  "CHANGE_COMPONENT_HEALTH_PAGE_NUMBER";

export const CHANGE_COMPONENT_HEALTH_SORT = "CHANGE_COMPONENT_HEALTH_SORT";
export const CHANGE_COMPONENT_HEALTH_SEARCH_TEXT =
  "CHANGE_COMPONENT_HEALTH_SEARCH_TEXT";

export const CHANGE_COMPONENT_HEALTH_NOTI_TYPE =
  "CHANGE_COMPONENT_HEALTH_NOTI_TYPE";

export const CHANGE_COMPONENT_HEALTH_DEVICE_TYPE =
  "CHANGE_COMPONENT_HEALTH_DEVICE_TYPE";
