/* TASKS */
export const GET_VMD = "GET_VMD";
export const GET_VMD_SUCCESS = "GET_VMD_SUCCESS";
export const GET_VMD_FAIL = "GET_VMD_FAIL";

export const CHANGE_VMD_PAGE_SIZE = "CHANGE_VMD_PAGE_SIZE";
export const CHANGE_VMD_PAGE_NUMBER = "CHANGE_VMD_PAGE_NUMBER";

export const CHANGE_VMD_SORT = "CHANGE_VMD_SORT";
export const CHANGE_VMD_SEARCH_TEXT = "CHANGE_VMD_SEARCH_TEXT";

export const CHANGE_VMD_NOTI_TYPE = "CHANGE_VMD_NOTI_TYPE";
