/* TASKS */
export const GET_CALLS = "GET_CALLS";
export const GET_CALLS_SUCCESS = "GET_CALLS_SUCCESS";
export const GET_CALLS_FAIL = "GET_CALLS_FAIL";

export const CHANGE_CALLS_PAGE_SIZE = "CHANGE_CALLS_PAGE_SIZE";
export const CHANGE_CALLS_PAGE_NUMBER = "CHANGE_CALLS_PAGE_NUMBER";

export const CHANGE_CALLS_SORT = "CHANGE_CALLS_SORT";
export const CHANGE_CALLS_SEARCH_TEXT = "CHANGE_CALLS_SEARCH_TEXT";

export const CHANGE_CALLS_NOTI_TYPE = "CHANGE_CALLS_NOTI_TYPE";
