/* TASKS */
export const GET_ANNOUNCEMENT = "GET_ANNOUNCEMENT";
export const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
export const GET_ANNOUNCEMENT_FAIL = "GET_ANNOUNCEMENT_FAIL";

export const CHANGE_ANNOUNCEMENT_PAGE_SIZE = "CHANGE_ANNOUNCEMENT_PAGE_SIZE";
export const CHANGE_ANNOUNCEMENT_PAGE_NUMBER =
  "CHANGE_ANNOUNCEMENT_PAGE_NUMBER";

export const CHANGE_ANNOUNCEMENT_SORT = "CHANGE_ANNOUNCEMENT_SORT";
export const CHANGE_ANNOUNCEMENT_SEARCH_TEXT =
  "CHANGE_ANNOUNCEMENT_SEARCH_TEXT";

export const CHANGE_ANNOUNCEMENT_NOTI_TYPE = "CHANGE_ANNOUNCEMENT_NOTI_TYPE";
